# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Unit Tests
      run: |
        python -m pytest 
    - name: Deploy to Heroku
      if: success()
      uses: two-tier-flask-app-cicd@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HRKU-05710f83-9cd6-412c-b80e-00c63fedfff6 }}  # Add your Heroku API key as a secret
        heroku_app_name: 'ujawal0011@gmail.com'  # Replace with your Heroku app name
        heroku_email: 'ujawal0011@gmail.com'  # Replace with your Heroku account email
